### Get all rooms
GET http://localhost:3000/api/rooms
Accept: application/json

### Get existing room
GET http://localhost:3000/api/rooms/1
Accept: application/json

### Get non-existing room (Should return 404)
GET http://localhost:3000/api/rooms/999
Accept: application/json
